apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csb-kafka
  name: csb-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csb-kafka
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: csb-kafka
    spec:
      containers:
      - image: nimbleplatform/csb-kafka:IMAGE_TAG
        imagePullPolicy: Always
        name: csb-kafka
        env:
          - name: MESSAGE_HUB_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: messagehub-credentials
                key: credentials.json
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
