apiVersion: v1
kind: Service
metadata:
  labels:
    app: csb-kafka
  name: csb-kafka
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: csb-kafka